# Generated by Django 3.0.6 on 2020-06-16 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20200615_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstate',
            name='index_position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='cost_per_work_hour',
            field=models.IntegerField(default=0, verbose_name='Kostnad per timma för arbete'),
        ),
        migrations.AlterField(
            model_name='company',
            name='currency',
            field=models.CharField(default='SEK', max_length=10, verbose_name='Valuta'),
        ),
    ]
