# Generated by Django 3.0.6 on 2020-06-29 20:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200617_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Company'),
        ),
        migrations.AlterField(
            model_name='projectstate',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Company'),
        ),
    ]
