# Generated by Django 3.0.5 on 2020-05-31 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200516_0111'),
        ('projects', '0004_auto_20200522_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productforproject',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='productforproject',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Antal'),
        ),
    ]
