# Generated by Django 3.0.6 on 2020-06-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200617_0149'),
        ('projects', '0009_project_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.ForeignKey(on_delete=models.SET('Missing'), to='users.ProjectState'),
        ),
    ]
