# Generated by Django 3.0.6 on 2020-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20200622_1724'),
        ('projects', '0010_auto_20200617_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=models.SET('Missing'), to='customers.Customer'),
            preserve_default=False,
        ),
    ]
