# Generated by Django 3.0.6 on 2020-07-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_projectstate'),
        ('projects', '0013_auto_20200708_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.ForeignKey(on_delete=models.SET('Missing'), to='company.ProjectState'),
        ),
    ]
