# Generated by Django 3.0.6 on 2020-07-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20200708_2344'),
        ('company', '0006_projecttype'),
        ('products', '0007_auto_20200708_2344'),
        ('projects', '0014_auto_20200708_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productforproject',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.Product', verbose_name='Produkt'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=models.SET(None), to='customers.Customer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='state',
            field=models.ForeignKey(on_delete=models.SET(None), to='company.ProjectState'),
        ),
    ]
