# Generated by Django 3.0.5 on 2020-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titel')),
                ('base_cost', models.FloatField(max_length=20, verbose_name='Bas kostnad')),
                ('scalable_cost', models.BooleanField(default=False, verbose_name='Enhets kostnad')),
                ('unit_label', models.CharField(max_length=100, verbose_name='Enhet titel')),
                ('unit_cost', models.FloatField(max_length=20, verbose_name='Kostnad enhet')),
            ],
        ),
    ]
