# Generated by Django 3.0.5 on 2020-05-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_auto_20200505_2201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='author',
            new_name='created_by',
        ),
    ]
