# Generated by Django 3.0.6 on 2020-06-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_accounting', '0002_remove_timereport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timereport',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
