# Generated by Django 3.0.6 on 2020-06-29 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20200628_2300'),
        ('time_accounting', '0003_timereport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereport',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Project'),
        ),
    ]
