# Generated by Django 3.0.6 on 2020-07-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20200708_2344'),
        ('company', '0003_auto_20200708_2344'),
        ('time_accounting', '0006_auto_20200701_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timereport',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company', verbose_name='Företag'),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Employee', verbose_name='Anställd'),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='hours',
            field=models.FloatField(verbose_name='Timmar'),
        ),
        migrations.AlterField(
            model_name='timereport',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.Project', verbose_name='Projekt'),
        ),
    ]
