# Generated by Django 3.0.6 on 2020-07-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_projectstate'),
        ('time_accounting', '0007_auto_20200708_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Datum')),
                ('time_start', models.TimeField(verbose_name='Start')),
                ('time_end', models.TimeField(verbose_name='Avslut')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company', verbose_name='Företag')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Employee', verbose_name='Anställd')),
            ],
        ),
    ]
