# Generated by Django 3.0.6 on 2020-07-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_accounting', '0008_workreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
