# Generated by Django 3.0.6 on 2020-06-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_customer_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactperson',
            name='email',
            field=models.EmailField(max_length=250, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Namn'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Telefon'),
        ),
    ]
