# Generated by Django 3.0.6 on 2020-07-08 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_employee_dummy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('created', models.DateField(auto_now_add=True)),
                ('currency', models.CharField(default='SEK', max_length=10, verbose_name='Valuta')),
                ('cost_per_work_hour', models.IntegerField(default=0, verbose_name='Kostnad per timma för arbete')),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='company.Company'),
        ),
    ]
