# Generated by Django 3.0.6 on 2020-07-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_projectstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectstate',
            name='display_table',
            field=models.BooleanField(default=True, verbose_name='Visa bräda'),
        ),
        migrations.AlterField(
            model_name='projectstate',
            name='index_position',
            field=models.IntegerField(verbose_name='Position'),
        ),
    ]
