# Generated by Django 3.0.6 on 2020-08-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_auto_20200805_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='cost',
            field=models.FloatField(blank=True, max_length=20, null=True, verbose_name='Kostnad (om ej satt kommer "Kostnad per arbetstimma" användas)'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Titel '),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Id'),
        ),
    ]
