# Generated by Django 3.0.6 on 2020-08-11 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200708_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='extra_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Kommentar'),
        ),
    ]
