# Generated by Django 3.0.6 on 2020-08-12 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_auto_20200805_0257'),
        ('products', '0008_auto_20200812_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTaskForProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_hours', models.FloatField(default=0, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Anteckning'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specification',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='Specification'),
        ),
        migrations.DeleteModel(
            name='WorkTask',
        ),
        migrations.AddField(
            model_name='worktaskforproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='worktaskforproduct',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.WorkType'),
        ),
    ]
